import bugMacro from './bugMacro'
import dataEditorMacro from './dataEditorMacro'
import devMacro from './devMacro'
import passagePreviewerMacro from './passagePreviewerMacro'
import progressiveTextMacro from './progressiveTextMacro'
import genCharMacro from './genCharMacro'